### ISSUE TITLE
What is `class_distribution.dt`?

### ISSUE THREAD

**Issue by AmitMY** [seokinj/BAGAN#2]
I am trying to run this model on MNIST and I get:
```
Traceback (most recent call last):
  File "gan.py", line 57, in <module>
    distribution = torch.load(os.path.join(args.distribution_dir,'class_distribution.dt'))['distribution']
  File "/home/nlp/amit/anaconda2/envs/mafat/lib/python2.7/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
IOError: [Errno 2] No such file or directory: 'distribution/class_distribution.dt'

```

**Comment by JayceeLee** [comment]
I think you should first run the "vae.py" file.
